name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
          - "head"

    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: RSpec tests
      run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    name: Standard Ruby Lint
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Standard
      run: bundle exec standardrb
